#Configuracion
#Fri May 15 14:39:53 MST 2026
=\=\=\=\=\=\=
<<<<<<<=HEAD
>>>>>>>=850ccc1c27121a39ba7efb48f1a28e14066ab1d4
registration.image.last.directory=/home/e/Pictures/memes
registration.window.height=500
registration.window.width=948
registration.window.x=659
registration.window.y=283
ui.theme=light
