#Configuracion
#Fri May 15 14:35:24 MST 2026
registration.image.last.directory=/home/e/Pictures/memes
registration.window.height=500
registration.window.width=948
registration.window.x=659
registration.window.y=283
ui.theme=light
