#Configuracion
#Sat May 09 16:13:38 MST 2026
registration.image.last.directory=/home/e/Pictures/memes
registration.window.height=500
registration.window.width=948
registration.window.x=745
registration.window.y=303
ui.theme=dark
